 let g:coc_global_extensions = [
       \'coc-tsserver',
       \'coc-eslint',
       \'coc-vetur',
       \'coc-emmet',
       \'coc-css',
       \'coc-highlight',
       \'coc-html',
       \'coc-json',
       \'coc-vimlsp',
       \'coc-explorer',
       \'coc-snippets',
       \'coc-sh',
       \'coc-tailwindcss',
       \'coc-java',
       \'coc-java-debug',
       \'coc-xml',
       \'coc-java-dependency',
       \'coc-sql',
       \'coc-groovy']

